"""A generic, single database configuration.

Revision ID: 057ad1d06abc
Revises: 0beccb58cd23
Create Date: 2026-01-26 16:24:30.098513

"""

from alembic import op
import sqlalchemy as sa

revision = "057ad1d06abc"
down_revision = "0beccb58cd23"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "samples", "collector_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column(
        "samples", "collector_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
