"""A generic, single database configuration.

Revision ID: 0a91667f7884
Revises: 5b0d325a5c14
Create Date: 2026-03-17 14:16:38.536856

"""
from alembic import op
import sqlalchemy as sa

revision = '0a91667f7884'
down_revision = '5b0d325a5c14'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company_profile', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('company_profile', 'logo')
    # ### end Alembic commands ###
