"""A generic, single database configuration.

Revision ID: 0beccb58cd23
Revises: d15166cc52f2
Create Date: 2026-01-26 14:14:18.839401

"""

from alembic import op
import sqlalchemy as sa

revision = "0beccb58cd23"
down_revision = "d15166cc52f2"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###
