"""A generic, single database configuration.

Revision ID: 0e937fbcd8a5
Revises: dd455d900f4f
Create Date: 2026-01-16 15:54:50.358828

"""
from alembic import op
import sqlalchemy as sa

revision = '0e937fbcd8a5'
down_revision = 'dd455d900f4f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('total_price', sa.Numeric(precision=10, scale=2), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('appointments', 'total_price')
    # ### end Alembic commands ###
