"""A generic, single database configuration.

Revision ID: 10e77ffba95f
Revises: c432e982e7eb
Create Date: 2026-01-13 02:32:17.467630

"""
from alembic import op
import sqlalchemy as sa

revision = '10e77ffba95f'
down_revision = 'c432e982e7eb'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
