"""A generic, single database configuration.

Revision ID: 13486b33af37
Revises: 395838095d3d
Create Date: 2026-03-06 17:19:28.459143

"""
from alembic import op
import sqlalchemy as sa

revision = '13486b33af37'
down_revision = '395838095d3d'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
