"""A generic, single database configuration.

Revision ID: 169a36c61422
Revises: 0a91667f7884
Create Date: 2026-03-19 14:45:54.216718

"""
from alembic import op
import sqlalchemy as sa

revision = '169a36c61422'
down_revision = '0a91667f7884'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_order_items', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('lab_order_items', 'created_at')
    # ### end Alembic commands ###
