"""A generic, single database configuration.

Revision ID: 18b4234e5ace
Revises: e8f12fbe4fa0
Create Date: 2026-01-26 19:16:06.421293

"""
from alembic import op
import sqlalchemy as sa

revision = '18b4234e5ace'
down_revision = 'e8f12fbe4fa0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_orders', sa.Column('appointment_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_orders', 'appointments', ['appointment_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_column('lab_orders', 'appointment_id')
    # ### end Alembic commands ###
