"""A generic, single database configuration.

Revision ID: 1b2d18bad7e0
Revises: e6323ad3e270
Create Date: 2026-04-13 20:15:09.575669

"""
from alembic import op
import sqlalchemy as sa

revision = '1b2d18bad7e0'
down_revision = 'e6323ad3e270'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'patients', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'patients', type_='foreignkey')
    op.drop_column('patients', 'created_by_id')
    # ### end Alembic commands ###
