"""A generic, single database configuration.

Revision ID: 24a4751ec7e4
Revises: f21c6f393934
Create Date: 2026-01-15 14:28:20.298755

"""
from alembic import op
import sqlalchemy as sa

revision = '24a4751ec7e4'
down_revision = 'f21c6f393934'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_name', sa.String(), nullable=False),
    sa.Column('category_description', sa.String(), nullable=False),
    sa.Column('date_added', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modified', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('added_by_id', sa.Integer(), nullable=True),
    sa.Column('modified_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['modified_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('appointments', sa.Column('start_time', sa.Time(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('end_time', sa.Time(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('preffered_mode', sa.String(), nullable=True))
    op.add_column('appointments', sa.Column('mode_of_payment', sa.String(), nullable=False))
    op.drop_index(op.f('ix_appointments_appointment_at'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_department_id'), table_name='appointments')
    op.drop_constraint(op.f('appointments_department_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'appointment_at')
    op.drop_column('appointments', 'department_id')
    op.add_column('tests', sa.Column('test_category_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_tests_test_category_id'), 'tests', ['test_category_id'], unique=False)
    op.create_foreign_key(None, 'tests', 'test_categories', ['test_category_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_index(op.f('ix_tests_test_category_id'), table_name='tests')
    op.drop_column('tests', 'test_category_id')
    op.add_column('appointments', sa.Column('department_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('appointments', sa.Column('appointment_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('appointments_department_id_fkey'), 'appointments', 'departments', ['department_id'], ['id'])
    op.create_index(op.f('ix_appointments_department_id'), 'appointments', ['department_id'], unique=False)
    op.create_index(op.f('ix_appointments_appointment_at'), 'appointments', ['appointment_at'], unique=False)
    op.drop_column('appointments', 'mode_of_payment')
    op.drop_column('appointments', 'preffered_mode')
    op.drop_column('appointments', 'end_time')
    op.drop_column('appointments', 'start_time')
    op.drop_table('test_categories')
    # ### end Alembic commands ###
