"""A generic, single database configuration.

Revision ID: 2641960b03e7
Revises: 8ae0f64963fd
Create Date: 2026-02-12 01:01:42.039515

"""
from alembic import op
import sqlalchemy as sa

revision = '2641960b03e7'
down_revision = '8ae0f64963fd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('short_code', sa.String(), nullable=True))
    op.alter_column('test_templates', 'min_reference_range',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('test_templates', 'max_reference_range',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('test_templates', 'max_reference_range',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('test_templates', 'min_reference_range',
               existing_type=sa.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('test_templates', 'short_code')
    # ### end Alembic commands ###
