"""A generic, single database configuration.

Revision ID: 27f473017403
Revises: 5e2a95f4471f
Create Date: 2026-03-06 12:13:38.590442

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "27f473017403"
down_revision = "5e2a95f4471f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "ALTER TABLE lab_order_items ALTER COLUMN sample_id TYPE INTEGER USING sample_id::integer"
    )
    op.alter_column(
        "lab_order_items",
        "sample_id",
        existing_type=sa.VARCHAR(length=80),
        type_=sa.Integer(),
        existing_nullable=True,
    )
    op.create_foreign_key(
        None, "lab_order_items", "samples", ["sample_id"], ["id"], ondelete="SET NULL"
    )
    op.add_column("samples", sa.Column("sample_type_id", sa.Integer(), nullable=False))
    op.alter_column(
        "samples",
        "collection_date",
        existing_type=postgresql.TIMESTAMP(timezone=True),
        type_=sa.DateTime(),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_index(op.f("ix_samples_collector_id"), table_name="samples")
    op.drop_constraint(op.f("samples_sample_type_fkey"), "samples", type_="foreignkey")
    op.drop_constraint(
        op.f("samples_phlebotomy_id_fkey"), "samples", type_="foreignkey"
    )
    op.create_foreign_key(
        None, "samples", "sample_categories", ["sample_type_id"], ["id"]
    )
    op.drop_column("samples", "sample_type")
    op.drop_column("samples", "phlebotomy_id")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "samples",
        sa.Column("phlebotomy_id", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "samples",
        sa.Column("sample_type", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "samples", type_="foreignkey")
    op.create_foreign_key(
        op.f("samples_phlebotomy_id_fkey"),
        "samples",
        "phlebotomies",
        ["phlebotomy_id"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("samples_sample_type_fkey"),
        "samples",
        "sample_categories",
        ["sample_type"],
        ["id"],
    )
    op.create_index(
        op.f("ix_samples_collector_id"), "samples", ["collector_id"], unique=False
    )
    op.alter_column(
        "samples",
        "collection_date",
        existing_type=sa.DateTime(),
        type_=postgresql.TIMESTAMP(timezone=True),
        existing_nullable=False,
        existing_server_default=sa.text("now()"),
    )
    op.drop_column("samples", "sample_type_id")
    op.drop_constraint(None, "lab_order_items", type_="foreignkey")
    op.alter_column(
        "lab_order_items",
        "sample_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
