"""A generic, single database configuration.

Revision ID: 2830f35412a7
Revises: 76c6eec2f765
Create Date: 2026-01-27 22:42:06.520766

"""
from alembic import op
import sqlalchemy as sa

revision = '2830f35412a7'
down_revision = '76c6eec2f765'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'sample_categories', ['category_name'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample_categories', type_='unique')
    # ### end Alembic commands ###
