"""A generic, single database configuration.

Revision ID: 2a46c1ad649f
Revises: 2641960b03e7
Create Date: 2026-02-12 02:25:51.738291

"""
from alembic import op
import sqlalchemy as sa

revision = '2a46c1ad649f'
down_revision = '2641960b03e7'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
