"""A generic, single database configuration.

Revision ID: 2b9e68c564d2
Revises: b6c4da528fea
Create Date: 2026-02-09 22:18:27.518152

"""
from alembic import op
import sqlalchemy as sa

revision = '2b9e68c564d2'
down_revision = 'b6c4da528fea'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('test_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=100), nullable=False),
    sa.Column('result', sa.Float(), nullable=False),
    sa.Column('unit', sa.String(), nullable=False),
    sa.Column('min_reference_range', sa.Float(), nullable=False),
    sa.Column('max_reference_range', sa.Float(), nullable=False),
    sa.Column('comment', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('test_templates')
    # ### end Alembic commands ###
