"""A generic, single database configuration.

Revision ID: 2de244f20964
Revises: f57937558186
Create Date: 2026-01-07 17:27:19.083839

"""
from alembic import op
import sqlalchemy as sa

revision = '2de244f20964'
down_revision = 'f57937558186'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
