"""A generic, single database configuration.

Revision ID: 3a23fbbe6d84
Revises: 9ac4e03d66f5
Create Date: 2026-03-16 23:23:10.454262

"""
from alembic import op
import sqlalchemy as sa

revision = '3a23fbbe6d84'
down_revision = '9ac4e03d66f5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('billings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bill_no', sa.String(length=50), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('total_billed', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billings_appointment_id'), 'billings', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_billings_bill_no'), 'billings', ['bill_no'], unique=True)
    op.create_index(op.f('ix_billings_patient_id'), 'billings', ['patient_id'], unique=False)
    op.create_table('billing_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('billing_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.Column('test_name', sa.String(length=255), nullable=False),
    sa.Column('price_at_booking', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['billing_id'], ['billings.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_billing_items_billing_id'), 'billing_items', ['billing_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_billing_items_billing_id'), table_name='billing_items')
    op.drop_table('billing_items')
    op.drop_index(op.f('ix_billings_patient_id'), table_name='billings')
    op.drop_index(op.f('ix_billings_bill_no'), table_name='billings')
    op.drop_index(op.f('ix_billings_appointment_id'), table_name='billings')
    op.drop_table('billings')
    # ### end Alembic commands ###
