"""A generic, single database configuration.

Revision ID: 3c6f2ac83dd1
Revises: 770453f9d483
Create Date: 2026-01-13 00:31:57.040366

"""
from alembic import op
import sqlalchemy as sa

revision = '3c6f2ac83dd1'
down_revision = '770453f9d483'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('visits', sa.Column('doctor_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_visits_doctor_id'), 'visits', ['doctor_id'], unique=False)
    op.create_foreign_key(None, 'visits', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_doctor_id'), table_name='visits')
    op.drop_column('visits', 'doctor_id')
    # ### end Alembic commands ###
