"""A generic, single database configuration.

Revision ID: 41173fbc68a6
Revises: 51b6efb719aa
Create Date: 2026-02-03 01:36:04.486519

"""
from alembic import op
import sqlalchemy as sa

revision = '41173fbc68a6'
down_revision = '51b6efb719aa'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
