"""A generic, single database configuration.

Revision ID: 49a6c789ca23
Revises: e392c8ce2750
Create Date: 2026-03-04 15:09:42.151558

"""
from alembic import op
import sqlalchemy as sa

revision = '49a6c789ca23'
down_revision = 'e392c8ce2750'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
