"""A generic, single database configuration.

Revision ID: 51b6efb719aa
Revises: b4b1ccd661b0
Create Date: 2026-02-03 00:59:17.872558

"""
from alembic import op
import sqlalchemy as sa

revision = '51b6efb719aa'
down_revision = 'b4b1ccd661b0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('transaction_date', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'transaction_date')
    # ### end Alembic commands ###
