"""A generic, single database configuration.

Revision ID: 549597fe3cd6
Revises: a8b9da4d3636
Create Date: 2026-01-07 18:09:46.921880

"""
from alembic import op
import sqlalchemy as sa

revision = '549597fe3cd6'
down_revision = 'a8b9da4d3636'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
