"""A generic, single database configuration.

Revision ID: 5a9d1d1b575a
Revises: fe123d926414
Create Date: 2026-03-13 00:12:20.806027

"""
from alembic import op
import sqlalchemy as sa

revision = '5a9d1d1b575a'
down_revision = 'fe123d926414'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'created_at')
    # ### end Alembic commands ###
