"""A generic, single database configuration.

Revision ID: 5b0d325a5c14
Revises: 3a23fbbe6d84
Create Date: 2026-03-17 07:57:18.102659

"""
from alembic import op
import sqlalchemy as sa

revision = '5b0d325a5c14'
down_revision = '3a23fbbe6d84'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billing_items', sa.Column('is_paid', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('billing_items', 'is_paid')
    # ### end Alembic commands ###
