"""A generic, single database configuration.

Revision ID: 5b29f2de5896
Revises: 1b2d18bad7e0
Create Date: 2026-04-13 20:33:42.331000

"""
from alembic import op
import sqlalchemy as sa

revision = '5b29f2de5896'
down_revision = '1b2d18bad7e0'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_orders', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'lab_orders', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'lab_orders', type_='foreignkey')
    op.drop_column('lab_orders', 'created_by_id')
    # ### end Alembic commands ###
