"""A generic, single database configuration.

Revision ID: 5b5848ca1938
Revises: bf8df900dabf
Create Date: 2026-03-06 12:50:20.090424

"""
from alembic import op
import sqlalchemy as sa

revision = '5b5848ca1938'
down_revision = 'bf8df900dabf'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
