"""A generic, single database configuration.

Revision ID: 5cb693e26962
Revises: acbe94a85df2
Create Date: 2026-02-27 09:08:20.227412

"""
from alembic import op
import sqlalchemy as sa

revision = '5cb693e26962'
down_revision = 'acbe94a85df2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('samples', 'test_requested')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('test_requested', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
