"""A generic, single database configuration.

Revision ID: 5cef3b7a884a
Revises: 18b4234e5ace
Create Date: 2026-01-26 19:20:26.265549

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "5cef3b7a884a"
down_revision = "18b4234e5ace"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lab_order_items",
        "stage",
        existing_type=postgresql.ENUM(
            "booking",
            "sampling",
            "running",
            "complete",
            "analyzing",
            "printing",
            "ended",
            name="lab_stage",
        ),
        type_=sa.String(),
        existing_nullable=False,
        existing_server_default=sa.text("'booking'::lab_stage"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lab_order_items",
        "stage",
        existing_type=sa.String(),
        type_=postgresql.ENUM(
            "booking",
            "sampling",
            "running",
            "complete",
            "analyzing",
            "printing",
            "ended",
            name="lab_stage",
        ),
        existing_nullable=False,
        existing_server_default=sa.text("'booking'::lab_stage"),
    )
    # ### end Alembic commands ###
