"""A generic, single database configuration.

Revision ID: 5de5d9728387
Revises: 5b5848ca1938
Create Date: 2026-03-06 13:21:51.842371

"""
from alembic import op
import sqlalchemy as sa

revision = '5de5d9728387'
down_revision = '5b5848ca1938'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('samples', sa.Column('phlebotomy_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_samples_phlebotomy_id'), 'samples', ['phlebotomy_id'], unique=False)
    op.create_foreign_key(None, 'samples', 'phlebotomies', ['phlebotomy_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.drop_index(op.f('ix_samples_phlebotomy_id'), table_name='samples')
    op.drop_column('samples', 'phlebotomy_id')
    # ### end Alembic commands ###
