"""A generic, single database configuration.

Revision ID: 5e2a95f4471f
Revises: 49a6c789ca23
Create Date: 2026-03-06 10:09:47.053218

"""
from alembic import op
import sqlalchemy as sa

revision = '5e2a95f4471f'
down_revision = '49a6c789ca23'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
