"""A generic, single database configuration.

Revision ID: 72749209cc86
Revises: 5de5d9728387
Create Date: 2026-03-06 13:42:34.358487

"""
from alembic import op
import sqlalchemy as sa

revision = '72749209cc86'
down_revision = '5de5d9728387'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
