"""A generic, single database configuration.

Revision ID: 73563c2f62bd
Revises: 169a36c61422
Create Date: 2026-03-30 22:57:02.296527

"""
from alembic import op
import sqlalchemy as sa

revision = '73563c2f62bd'
down_revision = '169a36c61422'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organization_prefixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('org_identifier', sa.String(), nullable=False),
    sa.Column('patient', sa.String(), nullable=False),
    sa.Column('test', sa.String(), nullable=False),
    sa.Column('appointment', sa.String(), nullable=False),
    sa.Column('invoice', sa.String(), nullable=False),
    sa.Column('bill', sa.String(), nullable=False),
    sa.Column('analyzer', sa.String(), nullable=False),
    sa.Column('payment', sa.String(), nullable=False),
    sa.Column('lab', sa.String(), nullable=False),
    sa.Column('radiology', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('organization_prefixes')
    # ### end Alembic commands ###
