"""A generic, single database configuration.

Revision ID: 76c6eec2f765
Revises: 5cef3b7a884a
Create Date: 2026-01-26 19:53:36.395465

"""

from alembic import op
import sqlalchemy as sa

revision = "76c6eec2f765"
down_revision = "5cef3b7a884a"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("status", sa.Boolean(), nullable=True))
    op.add_column(
        "tests",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tests", "created_at")
    op.drop_column("tests", "status")
    # ### end Alembic commands ###
