"""A generic, single database configuration.

Revision ID: 770453f9d483
Revises: 915cc3f9ebb2
Create Date: 2026-01-13 00:28:08.514635

"""
from alembic import op
import sqlalchemy as sa

revision = '770453f9d483'
down_revision = '915cc3f9ebb2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('visits', sa.Column('department_id', sa.Integer(), nullable=False))
    op.add_column('visits', sa.Column('status', sa.String(length=20), nullable=False))
    op.create_index(op.f('ix_visits_department_id'), 'visits', ['department_id'], unique=False)
    op.create_foreign_key(None, 'visits', 'departments', ['department_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'visits', type_='foreignkey')
    op.drop_index(op.f('ix_visits_department_id'), table_name='visits')
    op.drop_column('visits', 'status')
    op.drop_column('visits', 'department_id')
    op.drop_table('departments')
    # ### end Alembic commands ###
