"""A generic, single database configuration.

Revision ID: 78b97c3f3771
Revises: 2b9e68c564d2
Create Date: 2026-02-09 22:23:21.252460

"""
from alembic import op
import sqlalchemy as sa

revision = '78b97c3f3771'
down_revision = '2b9e68c564d2'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('test_templates', sa.Column('created_on', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('test_templates', 'created_on')
    # ### end Alembic commands ###
