"""A generic, single database configuration.

Revision ID: 799461c60a39
Revises: e3a1c68c484f
Create Date: 2026-01-23 20:07:51.178742

"""

from alembic import op
import sqlalchemy as sa

revision = "799461c60a39"
down_revision = "e3a1c68c484f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("phone_number", sa.String(), nullable=True))
    op.add_column(
        "users", sa.Column("gender", sa.String(), nullable=True, default="male")
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "gender")
    op.drop_column("users", "phone_number")
    # ### end Alembic commands ###
