"""A generic, single database configuration.

Revision ID: 79f69308bf56
Revises: fe59089048c6
Create Date: 2026-02-05 17:26:40.971532

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


revision = "79f69308bf56"
down_revision = "fe59089048c6"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tests", sa.Column("test_duration", sa.String(), nullable=True))
    op.add_column("tests", sa.Column("test_status", sa.Boolean(), nullable=True))
    op.drop_column("tests", "raw_test_results")
    op.drop_column("tests", "test_code")
    op.drop_column("tests", "test_results")
    op.drop_column("tests", "status")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "tests", sa.Column("status", sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.add_column(
        "tests",
        sa.Column(
            "test_results",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
    )
    op.add_column(
        "tests",
        sa.Column("test_code", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "tests",
        sa.Column("raw_test_results", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_column("tests", "test_status")
    op.drop_column("tests", "test_duration")
    # ### end Alembic commands ###
