"""A generic, single database configuration.

Revision ID: 7e2465b77ae4
Revises: ec582a56e597
Create Date: 2026-02-25 16:34:43.888684

"""
from alembic import op
import sqlalchemy as sa

revision = '7e2465b77ae4'
down_revision = 'ec582a56e597'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phlebotomies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('collected_by_id', sa.Integer(), nullable=True),
    sa.Column('collection_site', sa.Enum('hospital', 'clinic', 'ward', 'home_service', name='collectionsite'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['collected_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phlebotomies_appointment_id'), 'phlebotomies', ['appointment_id'], unique=False)
    op.create_index(op.f('ix_phlebotomies_patient_id'), 'phlebotomies', ['patient_id'], unique=False)
    op.add_column('samples', sa.Column('phlebotomy_id', sa.Integer(), nullable=True))
    op.alter_column('samples', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('samples', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_foreign_key(None, 'samples', 'phlebotomies', ['phlebotomy_id'], ['id'])
    op.drop_column('samples', 'sample_condition')
    op.add_column('tests', sa.Column('sample_category_id', sa.Integer(), nullable=True))
    op.add_column('tests', sa.Column('requires_phlebotomy', sa.Boolean(), nullable=False))
    op.create_foreign_key(None, 'tests', 'sample_categories', ['sample_category_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tests', type_='foreignkey')
    op.drop_column('tests', 'requires_phlebotomy')
    op.drop_column('tests', 'sample_category_id')
    op.add_column('samples', sa.Column('sample_condition', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'samples', type_='foreignkey')
    op.alter_column('samples', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('samples', 'priority',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('samples', 'phlebotomy_id')
    op.drop_index(op.f('ix_phlebotomies_patient_id'), table_name='phlebotomies')
    op.drop_index(op.f('ix_phlebotomies_appointment_id'), table_name='phlebotomies')
    op.drop_table('phlebotomies')
    # ### end Alembic commands ###
