"""A generic, single database configuration.

Revision ID: 894e04fcec2f
Revises: 24a4751ec7e4
Create Date: 2026-01-15 15:33:39.781675

"""
from alembic import op
import sqlalchemy as sa

revision = '894e04fcec2f'
down_revision = '24a4751ec7e4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('appointment_at', sa.DateTime(timezone=True), nullable=False))
    op.add_column('appointments', sa.Column('reason', sa.Text(), nullable=True))
    op.create_index(op.f('ix_appointments_appointment_at'), 'appointments', ['appointment_at'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_appointments_appointment_at'), table_name='appointments')
    op.drop_column('appointments', 'reason')
    op.drop_column('appointments', 'appointment_at')
    # ### end Alembic commands ###
