"""A generic, single database configuration.

Revision ID: 9093f20b5f05
Revises: 72749209cc86
Create Date: 2026-03-06 16:26:50.562695

"""
from alembic import op
import sqlalchemy as sa

revision = '9093f20b5f05'
down_revision = '72749209cc86'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phlebotomies', sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phlebotomies', 'completed_at')
    # ### end Alembic commands ###
