"""A generic, single database configuration.

Revision ID: 915cc3f9ebb2
Revises: a17059b2764e
Create Date: 2026-01-11 18:57:07.063270

"""
from alembic import op
import sqlalchemy as sa

revision = '915cc3f9ebb2'
down_revision = 'a17059b2764e'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
