"""A generic, single database configuration.

Revision ID: 96fccff9dc27
Revises: 10e77ffba95f
Create Date: 2026-01-13 22:11:14.552415

"""

from alembic import op
import sqlalchemy as sa

revision = "96fccff9dc27"
down_revision = "10e77ffba95f"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("visits", sa.Column("time_of_visit", sa.Time(), nullable=True))
    op.add_column(
        "visits", sa.Column("mode_of_payment", sa.String(length=15), nullable=True)
    )
    op.add_column("visits", sa.Column("date_of_visit", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("visits", "date_of_visit")
    op.drop_column("visits", "mode_of_payment")
    op.drop_column("visits", "time_of_visit")
    # ### end Alembic commands ###
