"""A generic, single database configuration.

Revision ID: 9a98cd6b5bbd
Revises: ef507721043f
Create Date: 2026-03-06 12:35:01.003900

"""
from alembic import op
import sqlalchemy as sa

revision = '9a98cd6b5bbd'
down_revision = 'ef507721043f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
