"""A generic, single database configuration.

Revision ID: 9ac4e03d66f5
Revises: 5a9d1d1b575a
Create Date: 2026-03-13 08:56:08.225979

"""
from alembic import op
import sqlalchemy as sa

revision = '9ac4e03d66f5'
down_revision = '5a9d1d1b575a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('image_url', sa.String(length=255), nullable=True))
    op.add_column('users', sa.Column('profile_picture', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'profile_picture')
    op.drop_column('patients', 'image_url')
    # ### end Alembic commands ###
