"""A generic, single database configuration.

Revision ID: a003226e2e3f
Revises: 96fccff9dc27
Create Date: 2026-01-13 22:24:58.706282

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "a003226e2e3f"
down_revision = "96fccff9dc27"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visits",
        "time_of_visit",
        existing_type=postgresql.TIME(),
        type_=sa.Time(timezone=True),
        existing_nullable=True,
    )
    op.drop_column("visits", "date_of_visit")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "visits",
        sa.Column(
            "date_of_visit", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
    )
    op.alter_column(
        "visits",
        "time_of_visit",
        existing_type=sa.Time(timezone=True),
        type_=postgresql.TIME(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
