"""A generic, single database configuration.

Revision ID: a17059b2764e
Revises: 549597fe3cd6
Create Date: 2026-01-11 18:54:25.968852

"""
from alembic import op
import sqlalchemy as sa

revision = 'a17059b2764e'
down_revision = '549597fe3cd6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
