"""A generic, single database configuration.

Revision ID: a3b5f5ee859b
Revises: ff81d82633e6
Create Date: 2026-03-06 12:29:17.823449

"""
from alembic import op
import sqlalchemy as sa

revision = 'a3b5f5ee859b'
down_revision = 'ff81d82633e6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sample_tests')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_tests',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('sample_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], name=op.f('sample_tests_sample_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], name=op.f('sample_tests_test_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('sample_tests_pkey'))
    )
    # ### end Alembic commands ###
