"""A generic, single database configuration.

Revision ID: a68e2a6f3388
Revises: f537d7365430
Create Date: 2026-02-03 15:03:57.608952

"""
from alembic import op
import sqlalchemy as sa

revision = 'a68e2a6f3388'
down_revision = 'f537d7365430'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('description', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('payments', 'description')
    # ### end Alembic commands ###
