"""A generic, single database configuration.

Revision ID: a8b9da4d3636
Revises: f00e8af5ffce
Create Date: 2026-01-07 17:41:26.486134

"""
from alembic import op
import sqlalchemy as sa

revision = 'a8b9da4d3636'
down_revision = 'f00e8af5ffce'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
