"""A generic, single database configuration.

Revision ID: acbe94a85df2
Revises: e877e5485e95
Create Date: 2026-02-25 23:30:02.483009

"""
from alembic import op
import sqlalchemy as sa

revision = 'acbe94a85df2'
down_revision = 'e877e5485e95'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
