"""A generic, single database configuration.

Revision ID: ad26e8ef9c83
Revises: a2f1ccca7c70
Create Date: 2026-01-16 03:33:18.546290

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "ad26e8ef9c83"
down_revision = "a2f1ccca7c70"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments",
        "start_time",
        existing_type=postgresql.TIME(timezone=True),
        type_=sa.Time(),
        existing_nullable=False,
    )
    op.alter_column(
        "appointments",
        "end_time",
        existing_type=postgresql.TIME(timezone=True),
        type_=sa.Time(),
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments",
        "end_time",
        existing_type=sa.Time(),
        type_=postgresql.TIME(timezone=True),
        existing_nullable=False,
    )
    op.alter_column(
        "appointments",
        "start_time",
        existing_type=sa.Time(),
        type_=postgresql.TIME(timezone=True),
        existing_nullable=False,
    )
    # ### end Alembic commands ###
