"""A generic, single database configuration.

Revision ID: af16f7ca56d5
Revises: fb0b137ca150
Create Date: 2026-02-05 14:16:01.483238

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "af16f7ca56d5"
down_revision = "fb0b137ca150"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visits",
        "time_of_visit",
        existing_type=postgresql.TIME(timezone=True),
        type_=sa.Time(),
        existing_nullable=True,
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "visits",
        "time_of_visit",
        existing_type=sa.Time(),
        type_=postgresql.TIME(timezone=True),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
