"""A generic, single database configuration.

Revision ID: b4966d898873
Revises: 894e04fcec2f
Create Date: 2026-01-15 20:27:27.580575

"""
from alembic import op
import sqlalchemy as sa

revision = 'b4966d898873'
down_revision = '894e04fcec2f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
