"""A generic, single database configuration.

Revision ID: b4b1ccd661b0
Revises: d1c74ae68b1a
Create Date: 2026-01-30 03:03:40.687887

"""
from alembic import op
import sqlalchemy as sa

revision = 'b4b1ccd661b0'
down_revision = 'd1c74ae68b1a'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('visits', 'department_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
