"""A generic, single database configuration.

Revision ID: bf8df900dabf
Revises: 9a98cd6b5bbd
Create Date: 2026-03-06 12:37:25.764798

"""
from alembic import op
import sqlalchemy as sa

revision = 'bf8df900dabf'
down_revision = '9a98cd6b5bbd'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
