"""A generic, single database configuration.

Revision ID: c432e982e7eb
Revises: ebb2317ba030
Create Date: 2026-01-13 02:28:44.457194

"""
from alembic import op
import sqlalchemy as sa

revision = 'c432e982e7eb'
down_revision = 'ebb2317ba030'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
