"""A generic, single database configuration.

Revision ID: c77df6938ce8
Revises: d3836e096148
Create Date: 2026-01-16 00:17:13.052125

"""
from alembic import op
import sqlalchemy as sa

revision = 'c77df6938ce8'
down_revision = 'd3836e096148'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointment_tests',
    sa.Column('appointment_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ),
    sa.PrimaryKeyConstraint('appointment_id', 'test_id')
    )
    op.drop_index(op.f('ix_appointments_test_id'), table_name='appointments')
    op.drop_constraint(op.f('appointments_test_id_fkey'), 'appointments', type_='foreignkey')
    op.drop_column('appointments', 'test_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('test_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('appointments_test_id_fkey'), 'appointments', 'tests', ['test_id'], ['id'])
    op.create_index(op.f('ix_appointments_test_id'), 'appointments', ['test_id'], unique=False)
    op.drop_table('appointment_tests')
    # ### end Alembic commands ###
