"""A generic, single database configuration.

Revision ID: d15166cc52f2
Revises: 799461c60a39
Create Date: 2026-01-26 14:10:01.483126

"""

from alembic import op
import sqlalchemy as sa

revision = "d15166cc52f2"
down_revision = "799461c60a39"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sample_categories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("category_name", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "samples",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("sample_type", sa.Integer(), nullable=False),
        sa.Column("appointment_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("test_requested", sa.JSON(), nullable=False),
        sa.Column("priority", sa.String(), nullable=True),
        sa.Column("storage_location", sa.String(), nullable=False),
        sa.Column(
            "collection_date",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("collector_id", sa.Integer(), nullable=False),
        sa.Column("collection_site", sa.String(), nullable=False),
        sa.Column("sample_condition", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["appointment_id"],
            ["appointments.id"],
        ),
        sa.ForeignKeyConstraint(
            ["collector_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patients.id"],
        ),
        sa.ForeignKeyConstraint(
            ["sample_type"],
            ["sample_categories.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_samples_appointment_id"), "samples", ["appointment_id"], unique=False
    )
    op.create_index(
        op.f("ix_samples_collector_id"), "samples", ["collector_id"], unique=False
    )
    op.create_index(
        op.f("ix_samples_patient_id"), "samples", ["patient_id"], unique=False
    )
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("users", "gender", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("users", "phone_number", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_index(op.f("ix_samples_patient_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_collector_id"), table_name="samples")
    op.drop_index(op.f("ix_samples_appointment_id"), table_name="samples")
    op.drop_table("samples")
    op.drop_table("sample_categories")
    # ### end Alembic commands ###
