"""A generic, single database configuration.

Revision ID: d1c74ae68b1a
Revises: d884ef6ae183
Create Date: 2026-01-28 21:46:23.449934

"""
from alembic import op
import sqlalchemy as sa

revision = 'd1c74ae68b1a'
down_revision = 'd884ef6ae183'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
