"""A generic, single database configuration.

Revision ID: d3836e096148
Revises: b4966d898873
Create Date: 2026-01-15 23:36:58.723250

"""
from alembic import op
import sqlalchemy as sa

revision = 'd3836e096148'
down_revision = 'b4966d898873'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('test_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_appointments_test_id'), 'appointments', ['test_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'tests', ['test_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_test_id'), table_name='appointments')
    op.drop_column('appointments', 'test_id')
    # ### end Alembic commands ###
