"""A generic, single database configuration.

Revision ID: d443de9b7195
Revises: 5b29f2de5896
Create Date: 2026-04-13 20:38:27.147605

"""
from alembic import op
import sqlalchemy as sa

revision = 'd443de9b7195'
down_revision = '5b29f2de5896'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('billings', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'billings', 'users', ['created_by_id'], ['id'])
    op.add_column('invoices', sa.Column('created_by_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoices', 'users', ['created_by_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_column('invoices', 'created_by_id')
    op.drop_constraint(None, 'billings', type_='foreignkey')
    op.drop_column('billings', 'created_by_id')
    # ### end Alembic commands ###
