"""A generic, single database configuration.

Revision ID: d884ef6ae183
Revises: 2830f35412a7
Create Date: 2026-01-27 23:30:20.683384

"""

from alembic import op
import sqlalchemy as sa

revision = "d884ef6ae183"
down_revision = "2830f35412a7"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "lab_results",
        "sample_id",
        existing_type=sa.VARCHAR(length=80),
        type_=sa.Integer(),
        existing_nullable=True,
        postgresql_using="sample_id::integer",
    )
    op.drop_index(op.f("ix_lab_results_sample_id"), table_name="lab_results")
    op.create_foreign_key(None, "lab_results", "samples", ["sample_id"], ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "lab_results", type_="foreignkey")
    op.create_index(
        op.f("ix_lab_results_sample_id"), "lab_results", ["sample_id"], unique=False
    )
    op.alter_column(
        "lab_results",
        "sample_id",
        existing_type=sa.Integer(),
        type_=sa.VARCHAR(length=80),
        existing_nullable=True,
    )
    # ### end Alembic commands ###
