"""A generic, single database configuration.

Revision ID: dd455d900f4f
Revises: ad26e8ef9c83
Create Date: 2026-01-16 13:29:18.464324

"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "dd455d900f4f"
down_revision = "ad26e8ef9c83"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "appointments", "end_time", existing_type=postgresql.TIME(), nullable=True
    )
    op.drop_column("appointments", "reason")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "appointments",
        sa.Column("reason", sa.TEXT(), autoincrement=False, nullable=True),
    )
    op.alter_column(
        "appointments", "end_time", existing_type=postgresql.TIME(), nullable=False
    )
    # ### end Alembic commands ###
