"""A generic, single database configuration.

Revision ID: e392c8ce2750
Revises: 5cb693e26962
Create Date: 2026-03-04 14:44:19.585997

"""
from alembic import op
import sqlalchemy as sa

revision = 'e392c8ce2750'
down_revision = '5cb693e26962'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoices', sa.Column('appointment_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_invoices_appointment_id'), 'invoices', ['appointment_id'], unique=False)
    op.create_foreign_key(None, 'invoices', 'appointments', ['appointment_id'], ['id'])
    op.drop_constraint(op.f('lab_results_test_no_key'), 'lab_results', type_='unique')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('lab_results_test_no_key'), 'lab_results', ['test_no'], postgresql_nulls_not_distinct=False)
    op.drop_constraint(None, 'invoices', type_='foreignkey')
    op.drop_index(op.f('ix_invoices_appointment_id'), table_name='invoices')
    op.drop_column('invoices', 'appointment_id')
    # ### end Alembic commands ###
