"""A generic, single database configuration.

Revision ID: e3a1c68c484f
Revises: 0e937fbcd8a5
Create Date: 2026-01-21 01:28:13.458966

"""
from alembic import op
import sqlalchemy as sa

revision = 'e3a1c68c484f'
down_revision = '0e937fbcd8a5'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
