"""A generic, single database configuration.

Revision ID: e877e5485e95
Revises: 7e2465b77ae4
Create Date: 2026-02-25 22:11:47.077445

"""
from alembic import op
import sqlalchemy as sa

revision = 'e877e5485e95'
down_revision = '7e2465b77ae4'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sample_tests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('test_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['sample_id'], ['samples.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['test_id'], ['tests.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('phlebotomies', sa.Column('status', sa.String(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phlebotomies', 'status')
    op.drop_table('sample_tests')
    # ### end Alembic commands ###
