"""A generic, single database configuration.

Revision ID: e8f12fbe4fa0
Revises: 057ad1d06abc
Create Date: 2026-01-26 17:49:43.898456

"""
from alembic import op
import sqlalchemy as sa

revision = 'e8f12fbe4fa0'
down_revision = '057ad1d06abc'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
