"""A generic, single database configuration.

Revision ID: e8f5bf0ab882
Revises: 272d6cc01063
Create Date: 2025-12-25 17:49:14.665035

"""
from alembic import op
import sqlalchemy as sa

revision = 'e8f5bf0ab882'
down_revision = '272d6cc01063'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
