"""A generic, single database configuration.

Revision ID: ebb2317ba030
Revises: 3c6f2ac83dd1
Create Date: 2026-01-13 00:50:01.396841

"""
from alembic import op
import sqlalchemy as sa

revision = 'ebb2317ba030'
down_revision = '3c6f2ac83dd1'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
