"""A generic, single database configuration.

Revision ID: ec582a56e597
Revises: 2a46c1ad649f
Create Date: 2026-02-16 18:47:47.597007

"""
from alembic import op
import sqlalchemy as sa

revision = 'ec582a56e597'
down_revision = '2a46c1ad649f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patients', sa.Column('age', sa.Integer(), nullable=False))
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patients', 'age')
    # ### end Alembic commands ###
