"""A generic, single database configuration.

Revision ID: edc1d715297c
Revises: 9093f20b5f05
Create Date: 2026-03-06 16:52:04.306753

"""
from alembic import op
import sqlalchemy as sa

revision = 'edc1d715297c'
down_revision = '9093f20b5f05'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
