"""A generic, single database configuration.

Revision ID: ef507721043f
Revises: a3b5f5ee859b
Create Date: 2026-03-06 12:31:57.494839

"""
from alembic import op
import sqlalchemy as sa

revision = 'ef507721043f'
down_revision = 'a3b5f5ee859b'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
