"""A generic, single database configuration.

Revision ID: f00e8af5ffce
Revises: 2de244f20964
Create Date: 2026-01-07 17:37:12.634396

"""
from alembic import op
import sqlalchemy as sa

revision = 'f00e8af5ffce'
down_revision = '2de244f20964'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
