"""A generic, single database configuration.

Revision ID: f21c6f393934
Revises: a003226e2e3f
Create Date: 2026-01-14 01:47:36.624042

"""
from alembic import op
import sqlalchemy as sa

revision = 'f21c6f393934'
down_revision = 'a003226e2e3f'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('appointments', sa.Column('doctor_id', sa.Integer(), nullable=False))
    op.add_column('appointments', sa.Column('department_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_appointments_department_id'), 'appointments', ['department_id'], unique=False)
    op.create_index(op.f('ix_appointments_doctor_id'), 'appointments', ['doctor_id'], unique=False)
    op.create_foreign_key(None, 'appointments', 'departments', ['department_id'], ['id'])
    op.create_foreign_key(None, 'appointments', 'users', ['doctor_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_constraint(None, 'appointments', type_='foreignkey')
    op.drop_index(op.f('ix_appointments_doctor_id'), table_name='appointments')
    op.drop_index(op.f('ix_appointments_department_id'), table_name='appointments')
    op.drop_column('appointments', 'department_id')
    op.drop_column('appointments', 'doctor_id')
    # ### end Alembic commands ###
