"""A generic, single database configuration.

Revision ID: f537d7365430
Revises: 41173fbc68a6
Create Date: 2026-02-03 01:39:22.173144

"""
from alembic import op
import sqlalchemy as sa

revision = 'f537d7365430'
down_revision = '41173fbc68a6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
