"""A generic, single database configuration.

Revision ID: f57937558186
Revises: e8f5bf0ab882
Create Date: 2026-01-07 16:15:22.598707

"""
from alembic import op
import sqlalchemy as sa

revision = 'f57937558186'
down_revision = 'e8f5bf0ab882'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
