"""A generic, single database configuration.

Revision ID: fb0b137ca150
Revises: a68e2a6f3388
Create Date: 2026-02-05 13:57:15.338135

"""
from alembic import op
import sqlalchemy as sa

revision = 'fb0b137ca150'
down_revision = 'a68e2a6f3388'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
