"""A generic, single database configuration.

Revision ID: fe123d926414
Revises: 619053e92ff6
Create Date: 2026-03-12 18:29:11.184319

"""
from alembic import op
import sqlalchemy as sa

revision = 'fe123d926414'
down_revision = '619053e92ff6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('is_paid', sa.Boolean(), nullable=False))
    op.add_column('invoice_items', sa.Column('lab_order_item_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'invoice_items', 'lab_order_items', ['lab_order_item_id'], ['id'])
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'invoice_items', type_='foreignkey')
    op.drop_column('invoice_items', 'lab_order_item_id')
    op.drop_column('invoice_items', 'is_paid')
    # ### end Alembic commands ###
