"""A generic, single database configuration.

Revision ID: fe59089048c6
Revises: bb36deabc085
Create Date: 2026-02-05 16:32:23.112044

"""
from alembic import op
import sqlalchemy as sa

revision = 'fe59089048c6'
down_revision = 'bb36deabc085'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'status',
               existing_type=sa.BOOLEAN(),
               type_=sa.String(),
               existing_nullable=True)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tests', 'status',
               existing_type=sa.String(),
               type_=sa.BOOLEAN(),
               existing_nullable=True)
    # ### end Alembic commands ###
