"""A generic, single database configuration.

Revision ID: ff81d82633e6
Revises: b05cae48c3f6
Create Date: 2026-03-06 12:27:36.618137

"""
from alembic import op
import sqlalchemy as sa

revision = 'ff81d82633e6'
down_revision = 'b05cae48c3f6'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lab_order_items_analyzer_id_fkey'), 'lab_order_items', type_='foreignkey')
    op.drop_column('lab_order_items', 'external_sample_id')
    op.drop_column('lab_order_items', 'analyzer_id')
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('lab_order_items', sa.Column('analyzer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('lab_order_items', sa.Column('external_sample_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('lab_order_items_analyzer_id_fkey'), 'lab_order_items', 'analyzers', ['analyzer_id'], ['id'])
    # ### end Alembic commands ###
